# Generated by Django 4.0.4 on 2022-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productbrand_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=400, unique=True, verbose_name='عنوان در url'),
        ),
    ]
