# Generated by Django 4.0.4 on 2022-07-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
