# Generated by Django 4.0.4 on 2022-07-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_product_file'),
        ('stripe_payment_module', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='کالا'),
        ),
    ]
