# Generated by Django 3.2.14 on 2022-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charisma_product_module', '0003_auto_20220718_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='مالیات'),
        ),
    ]
