# Generated by Django 4.0.4 on 2022-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_sitebanner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(upload_to='images/banners/', verbose_name='تصویر بنر'),
        ),
    ]
