# Generated by Django 4.0.4 on 2022-05-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_sitebanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='is_active',
            field=models.BooleanField(default=True, max_length=200, verbose_name='فعال/غیر فعال'),
        ),
    ]
