# Generated by Django 4.0.4 on 2022-04-28 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 4, 28), verbose_name='تاریخ ثبت مقاله'),
            preserve_default=False,
        ),
    ]
