# Generated by Django 4.0.4 on 2022-05-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
